site_name: Luna
site_url: https://sanjeetbalamurugan.github.io/Luna
theme:
  name: material

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_api.py
  - literate-nav
  - section-index
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

nav:
  - Home: index.md
  - API Reference: reference/index.md