site_name: Luna
site_url: https://sanjeetbalamurugan.github.io/Luna
theme:
  name: material
  palette:
    # Palette toggle for dark mode (default)
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Helvetica
    code: Helvetica
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_api.py
  - literate-nav
  - section-index
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
nav:
  - Home: index.md
  - API Reference: reference/index.md